services:
    linkTorch-postgres:
        image: postgres:15-alpine
        container_name: linktorch_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    linkTorch-auth:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: linktorch_app
        restart: unless-stopped
        ports:
            - '${APP_PORT}:3000'
        env_file:
            - .env
        depends_on:
            - linkTorch-postgres
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    postgres_data:
    pgadmin_data:
