#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "📝 Validating commit message format..."
npx --no -- commitlint --edit ${1}
echo "✅ Commit message format is valid."npx --no -- commitlint --edit $1
